website/__init__.py
from flask import Flask, url_for, render_template
from .database import create_database, create_table_contact

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'mulinhas'

    from .routes import routes
    app.register_blueprint(routes, url_prefix='/')

    try: create_database()
    except: pass
    
    try: create_table_contact()
    except: pass 

    return app

website/routes.py
from flask import Flask, request, Blueprint, render_template, url_for
from .database import inserir_dados, buscarInfo

routes = Blueprint('routes',__name__)


@routes.route("/")
def i():
    return render_template("home.html")

@routes.route("/home")
def home():
    return render_template("home.html")

@routes.route("/contato",methods = ["POST","GET"])
def contato():
    if request.method == "POST":
        email = request.form.get("email")
        assunto = request.form.get("assunto")
        descricao = request.form.get("desc")
        inserir_dados(email, assunto, descricao)
        return render_template("contato.html")
    return render_template("contato.html")

@routes.route("/quemSomos")
def who():                  
    return render_template("quemSomos.html")


@routes.route("/info")
def info():
    info = buscarInfo()
    if len(info) > 0:
        return render_template("info.html", info = buscarInfo())
    else: 
        return render_template("info.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
</head>
<header class="body">
    <div class="cabecalho">
        <img src="../static/img/logo.png" alt="logo.png">
        <ul>
            <li> <a href="home">Home</li></a>
            <li> <a href="quemSomos">Quem Somos</li></a>
            <li> <a href="contato">Contato</li></a>
            <li> <a href="info">Informações</li></a>

        </ul>

        
    </div>
    <div class="conteudo">
      
    {% block content %}

    {% endblock %}

    </div>
</header>
</html>

website/templates/contato.html
{% extends "base.html" %}

{% block content %}

   <body background="static/img/fundo2.jpeg">

        <h3>Entre em contato</h3>  
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestias, tempora expedita sapiente illum quidem, aut fugit perferendis rem adipisci modi facere animi doloribus ex voluptate veritatis facilis, earum similique tenetur!</p>
        <hr>
        <div class="form">
            <form action="{{url_for('routes.contato')}}"method="POST">
                <label for="email">Email:</label><br>
                <input type="text" name="email" id="email">
                <br>
                <label for="assunto">Assunto:</label><br>
                <input type="text" name="assunto" id="assunto"><br>
                <label for="desc">Descrição:</label><br>
                <textarea name="desc" id="desc" cols="30" rows="5"></textarea><br>
                <input type="submit" value="Enviar"></input>
            </form>
        </div>
        <br><br><br>
        <h4>Todos os direitos reservados</h4>
    </body>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block content %}
      
    <body background="static/img/fundo.jpeg">
    
        
        <img class="img" src="../static/img/tecnologia.jpeg" alt="imagem de capa">
        <h1>Sobre a universidade</h1>
        <p class="pg">
        Lipsum dolor sit amet, consectetur adipisicing elit. Sint exercitationem, ducimus provident placeat sit maxime ullam tempore accusamus reprehenderit dolores libero incidunt eius, totam quos. At aut id corrupti quibusdam.Lipsum dolor sit amet, consectetur adipisicing elit. Sint exercitationem, ducimus provident placeat sit maxime ullam tempore accusamus reprehenderit dolores libero incidunt eius, totam quos. At aut id corrupti quibusdam.Lipsum dolor sit amet, consectetur adipisicing elit. Sint exercitationem, ducimus provident placeat sit maxime ullam tempore accusamus reprehenderit dolores libero incidunt eius, totam quos.
        </p>
        <h4>Todos os direitos reservados</h4>
    </div>
    </body>
{% endblock %}

website/templates/info.html
{% extends "base.html" %}

{% block content %}

   <body background="static/img/fundo2.jpeg">

        <h3>Veja abaixo as informações de quem entrou em contato</h3>  
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestias, tempora expedita sapiente illum quidem, aut fugit perferendis rem adipisci modi facere animi doloribus ex voluptate veritatis facilis, earum similique tenetur!</p>
        <hr>
       
        {% if info %}
    <h1>Últimos emails recebidos:</h1>

    <table class="tabela">
        <tr>
            <th>Email</th>
            <th>Assunto</th>
            <th>Descrição</th>
        </tr>
        {% for i in info %}
        <tr>
            <td> {{ i[0] }} </td>
            <td> {{ i[1] }} </td>
            <td> {{ i[2] }} </td>
        </tr>
        {% endfor %}

    </table> 
{% else %}
    <h1>Ainda não recebemos nenhum email.</h1>
{% endif %}
     
<br><br><br>

        <h4>Todos os direitos reservados</h4>
    </body>
{% endblock %}

website/templates/quemSomos.html
{% extends "base.html" %}

{% block content %}
<body background="static/img/fundo2.jpeg">
    <h3>Quem somos</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate aperiam aut tempora doloribus mollitia laboriosam repellendus, quam officia, distinctio nesciunt dolorem natus blanditiis hic. Nam repudiandae cumque iusto illum consequuntur.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate aperiam aut tempora doloribus mollitia laboriosam repellendus, quam officia, distinctio nesciunt dolorem natus blanditiis hic. Nam repudiandae cumque iusto illum consequuntur!</p>

    <h3>5 motivos para estudar</h3>
    <ol>
        <li>Material sempre atualizado</li>
        <li>Tablets em sala de aula</li>
        <li>Professores renomados</li>
        <li>Universidade bem avaliada</li>
        <li>Ótima localização</li>
      </ol> 
      <hr>
      <h3>Objetivos</h3>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum omnis quia delectus esse repudiandae necessitatibus at? Accusantium, ea. Id laboriosam repudiandae rem illo. Ullam alias beatae laudantium totam ab sunt.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum omnis quia delectus esse repudiandae necessitatibus at? Accusantium, ea. Id laboriosam repudiandae rem illo. Ullam alias beatae laudantium totam ab sunt.
      </p>
      <h4>Todos os direitos reservados</h4>

</body>
    {% endblock %}
    